-- "Nuclear Option": Disable Row Level Security entirely for this table.
-- Since this is a public calculator and we want anyone to be able to save/update quotes
-- generated by the system (protected by a random ID), this is the simplest path to unblock.

alter table public.quotes disable row level security;
